lidar_node:
  serial_port: /dev/ttyUSB0
  frame_id: laser_frame
  angle_compensate: true
  scan_mode: Standard


realsense_node:
  serial_port: /dev/ttyUSB1


motor_node:
  serial_port: /dev/ttyTHS1
  baud_rate: 115200



