lidar_node:
  serial_port: /dev/ttyUSB0


realsense_node:
  serial_port: /dev/ttyUSB1


motor_node:
  serial_port: /dev/ttyTHS1
  baud_rate: 115200

xacro_filepath: /home/colin/Desktop/ros2_ws/src/minibot/description/robot.urdf.xacro


