<?xml version="1.0"?>








<robot xmlns:xacro="http://www.ros.org/wiki/xacro">



    <!-- EDIT ROBOT DESCRIPTION HERE -->
    <xacro:property name="chassis_width" value="0.05" />
    <xacro:property name="chassis_length" value="0.266" />
    <xacro:property name="chassis_height" value="0.05" />


    <xacro:property name="wheel_radius" value="0.08" />
    <xacro:property name="wheel_thickness" value="0.04" />

    <xacro:include filename="inertial_macros.xacro" />

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>

    <material name="magenta">
        <color rgba="1 0 1 1" />
    </material>

    <link name="world_link">

    </link>

    <joint name="world_to_base_joint" type="fixed">
        <parent link="world_link" />
        <child link="base_link" />
        <origin xyz="0 0 0.02" />
    </joint>
    
    <!-- BASE LINK -->

    <link name="base_link">
        
    </link>

    <!-- BASE_FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />

    </joint>

    <link name="base_footprint" >
    </link>


    <!-- CHASSIS -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 0" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${wheel_radius}" />
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0 0 ${wheel_radius/2}" />
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
            
        </collision>
        <xacro:inertial_box mass="2.0" x="${chassis_width}" y="${chassis_length}" z="${chassis_height}">
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="chassis2_joint" type="fixed">
        <parent link="chassis" />
        <child link="chassis2" />
        <origin xyz="0 0 0" />
    </joint>

    <link name="chassis2">
        <visual>
            <origin xyz="0.133 0 ${wheel_radius}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0 0 ${wheel_radius/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            
        </collision>
        <xacro:inertial_box mass="2.0" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0.133 0 ${wheel_radius}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis2">
        <material>Gazebo/White</material>
    </gazebo>


    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="0 ${chassis_length/2} ${wheel_radius}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>


    <link name="right_wheel">

        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.5" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="3" />
        <mu2 value="3" />
    </gazebo>
    



    <!-- LEFT WHEEL LINK -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="0 ${-chassis_length/2} ${wheel_radius}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>


    <link name="left_wheel">

        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.5" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="3" />
        <mu2 value="3" />
    </gazebo>



    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis" />
        <child link="caster_wheel" />
        <origin xyz="0.225 0 0.05" />

    </joint>

    

    <link name="caster_wheel" >
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <material name="black" />
        </visual>


        <collision>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
        </collision>
    </link>
    

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001" />
        <mu2 value="0.001" />
    </gazebo>

</robot>